### ISSUE TITLE
Does not work with ver5.6.0

### ISSUE THREAD

**Issue by SOGAKEN** [inkdropapp/gfm-alerts#2]
It doesn't seem to work with the newer inkdrop versions.
ver 5.6.0

<img width="1362" alt="スクリーンショット 2023-11-19 8 28 58" src="https://github.com/Keisir/inkdrop-gfm-blockquote-admonitions/assets/58077058/a138ca3f-de92-4ef1-a0ec-46a98e1ecba1">

**Comment by Keisir** [comment]
Hey,
it should work with Inkdrop v5.6.0. I'm currently using it with v5.6.2-beta.0.

Can you check for errors in the console?
<details>
<summary>More Info</summary>
<img src="https://github.com/Keisir/inkdrop-gfm-blockquote-admonitions/assets/100614278/4f7c7574-fd95-4769-8d5c-47e42bf1c925" />
</details>

**Comment by SOGAKEN** [comment]
Thank you.
I found the cause.
The cause was the official plugin [breaks].
I turned it off and it worked fine.

**Comment by Keisir** [comment]
I'm glad to hear that you were able to fix the problem.
I'll see if I can support this plugin.
