### ISSUE TITLE
Make it an official plugin 🥳

### ISSUE THREAD

**Issue by craftzdog** [inkdropapp/gfm-alerts#3]
Hey @Keisir,

Could you add me to a collaborator so that I can move this repo to https://github.com/inkdropapp ?

I'll republish the plugin as "alerts" [as GitHub calls them in their official docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

**Comment by Keisir** [comment]
Hey @craftzdog!
I have sent out an invitation. Feel free to make it an official plugin.
Just let me know if you need anything else.

**Comment by craftzdog** [comment]
Thank you! But it looks like I can't transfer this repository to the inkdropapp organization 🤔
I guess only you can do that: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by Keisir** [comment]
I have tried to transfer ownership to `inkdropapp`, but it does not work. It says that I don't have permission to create public repositories in this organisation.
Instead, I have transferred the repository to your private account. Then you can transfer it to the inkdropapp organisation yourself.

I hope that this will work.

**Comment by craftzdog** [comment]
it works!! Thanks so much 🙌
