### ISSUE TITLE
line breaks with two spaces or '\' not working

### ISSUE THREAD

**Issue by craftzdog** [inkdropapp/gfm-alerts#7]
Hi @Keisir ,

It looks like this module breaks the support for inserting line breaks with two spaces or '\\' at the end of lines in quotes.
Could you look into it?

## How to reproduce

The first line ends with two spaces:

```markdown
> Each time you increase the amount of code, your software grows exponentially more complicated.  
> -- DHH, Getting Real
```

## Expected behavior

It should insert `<br>` at the end of the first line like so: 

> Each time you increase the amount of code, your software grows exponentially more complicated.  
> -- DHH, Getting Real

## Actual behavior

`<br>` is not inserted:

![Screenshot 2024-03-14 at 10 03 38](https://github.com/inkdropapp/gfm-alerts/assets/1332805/9ff8963d-8513-4a87-ae38-8e1ee599517e)

**Comment by Keisir** [comment]
Hey,
I will have a look at this at the weekend.

**Comment by Keisir** [comment]
I started looking into this. I may have found a solution but haven't had a chance to try it out yet. I will do it tomorrow.
